# Generated by Django 4.0.4 on 2022-07-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
